[Feature] Add rsync tilt path
tilt-dev/tilt-extensions pull request #479
Opened 2023-02-07 19:03 UTC by coler-j

Adds functionality to customize the rsync path on the container to resolve potential permission errors if the execution user does not have permission to modify the containers `/bin` directory. Resolves https://github.com/tilt-dev/tilt-extensions/issues/478

Adds the `tilt_rsync_path` parameter to the `syncback` command.

Used like:

```
syncback("python-syncback", 
    "deploy/syncback-containers", 
    "/root/", 
    paths=['main.py'],  
    target_dir=python, 
    container="python", 
    namespace="syncback-test",
    tilt_rsync_path="/some/remote/path/"
)
```

2023-02-07 20:14 UTC, nicksieger requested changes
Thanks for this pull request. Overall it looks good to me. Would you be ok with naming the starlark parameter just `rsync_path`? I added suggested changes you can accept if you want. I think I got them all correct but please check!

2023-02-07 20:14 UTC, nicksieger commented on syncback/Tiltfile
> +def syncback_command_args(k8s_object, src_dir, ignore=None, delete=False, paths=None, target_dir='.', container='', namespace='', verbose=False, tilt_rsync_path=tilt_rsync_path):
```suggestion
def syncback_command_args(k8s_object, src_dir, ignore=None, delete=False, paths=None, target_dir='.', container='', namespace='', verbose=False, rsync_path=tilt_rsync_path):
```

2023-02-07 20:14 UTC, nicksieger commented on syncback/Tiltfile
> +    :param tilt_rsync_path (str, optional): A path where the remote containers `rsync` executable is located. Defaults to `/bin/rsync.tilt`.
```suggestion
    :param rsync_path (str, optional): A path where the remote containers `rsync` executable is located. Defaults to looking for rsync on the container's $PATH or `/bin/rsync.tilt` uploaded by Tilt.
```

2023-02-07 20:14 UTC, nicksieger commented on syncback/Tiltfile
> +def syncback(name, k8s_object, src_dir, ignore=None, delete=False, paths=None, target_dir='.', container='', namespace='', verbose=False, labels=[], resource_deps=[], tilt_rsync_path=tilt_rsync_path)
```suggestion
def syncback(name, k8s_object, src_dir, ignore=None, delete=False, paths=None, target_dir='.', container='', namespace='', verbose=False, labels=[], resource_deps=[], rsync_path=tilt_rsync_path):
```

2023-02-07 20:14 UTC, nicksieger commented on syncback/Tiltfile
> +                               verbose=verbose, tilt_rsync_path=tilt_rsync_path)
```suggestion
                               verbose=verbose, rsync_path=rsync_path)
```

2023-02-07 20:23 UTC, nicksieger commented
Ugh, I'm sorry, it looks like GH suggestions don't add `Signed-off-by:` to the commits. Would you mind just squashing them all, ensuring you have sign off, and do a `git push --force-with-lease` to your PR branch?

2023-02-07 20:31 UTC, coler-j commented
@nicksieger I have to run to an appointment, but will clean this up first thing tomorrow AM (EST)

2023-02-08 13:54 UTC, coler-j commented
@nicksieger does that work?

2023-02-08 15:41 UTC, nicksieger approved these changes

2023-02-08 15:41 UTC, nicksieger commented
Thanks for the improvement!

2023-02-08 15:42 UTC, merged

2023-02-08 15:43 UTC, coler-j commented
Thanks @nicksieger how long until this change is released / useable?

2023-02-15 20:05 UTC, da-code-a commented
I'm still getting a Permission Denied error. Should I make a new issue or report my output on #478 ?